name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.0.2
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  functional_data: 0.3.0
  intl: 0.16.1
  flutter_reactive_ble:
    path: ../packages/flutter_reactive_ble
  reactive_ble_mobile:
    path: ../packages/reactive_ble_mobile

  provider: 4.3.3

dev_dependencies:
  build_runner: 1.11.0
  dependency_validator: 2.0.3
  functional_data_generator: 0.3.8

flutter:
  uses-material-design: true
