name: reactive_ble_mobile
description: Official Android and iOS implementation for the flutter_reactive_ble plugin.
version: 5.0.2
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: 1.1.4
  reactive_ble_platform_interface: 
    path: ../reactive_ble_platform_interface
dev_dependencies:
  build_runner: 1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.signify.hue.flutterreactiveble
        pluginClass: ReactiveBlePlugin
      ios:
        pluginClass: ReactiveBlePlugin
