name: flutter_reactive_ble
description: Reactive Bluetooth Low Energy (BLE) plugin that can communicate with multiple devices
version: 5.0.2
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: reactive_ble_mobile
      ios:
        default_package: reactive_ble_mobile

dependencies:
  collection: any
  flutter:
    sdk: flutter
  functional_data: 0.3.0
  meta: ^1.2.4
  reactive_ble_mobile: 
    path: ../reactive_ble_mobile
  reactive_ble_platform_interface: 
    path: ../reactive_ble_platform_interface

dev_dependencies:
  build_runner: 1.11.0
  functional_data_generator: 0.3.8
  
