name: reactive_ble_platform_interface
description: Platform interface for the flutter_reactive_ble_project 
version: 5.0.2
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: any
  flutter:
    sdk: flutter
  functional_data: 0.3.0
  meta: ^1.2.4

  plugin_platform_interface: 1.0.3

dev_dependencies:
  build_runner: 1.11.0
  functional_data_generator: 0.3.8

flutter:
